In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import plotly.plotly as py
import plotly.graph_objs as go

In [2]:
path = './df.xlsx'

In [3]:
df = pd.read_excel(path)

In [4]:
df.head()

,Country,Type,Aircraft Damage,Aircraft Category,Amateur Built,Number of Engines,Purpose of Flight,Report Status,Injury Severity
0,United States,Accident,Substantial,Airplane,Yes,1,Personal,Preliminary,Non-Fatal
1,United States,Accident,Substantial,Airplane,No,1,Instructional,Preliminary,Non-Fatal
2,United States,Accident,Substantial,Airplane,Yes,1,Personal,Preliminary,Non-Fatal
3,United States,Accident,Substantial,Airplane,No,1,Personal,Preliminary,Non-Fatal
4,United States,Accident,Substantial,Airplane,No,1,Instructional,Preliminary,Non-Fatal

In [5]:
cleanup = {'Type' : {'Accident':1, 'Incident':0},
           'Amateur Built' : {'Yes':1, 'No':0},
           'Injury Severity' : {'Non-Fatal':0,'Fatal':1}}
df.replace(cleanup, inplace=True)

# for i in df:
#     i['Type'] = i['Type'].map({'Accident':1, 'Incident':0}).astype(int)
#     i['Amateur Built'] = i['Amateur Built'].map({'Yes':1, 'No':0}).astype(int)
#     i['Injury Severity'] = i['Injury Severity'].map({'Non-Fatal':0,'Fatal':1}).astype(int)

df.head()

,Country,Type,Aircraft Damage,Aircraft Category,Amateur Built,Number of Engines,Purpose of Flight,Report Status,Injury Severity
0,United States,1,Substantial,Airplane,1.0,1,Personal,Preliminary,0
1,United States,1,Substantial,Airplane,0.0,1,Instructional,Preliminary,0
2,United States,1,Substantial,Airplane,1.0,1,Personal,Preliminary,0
3,United States,1,Substantial,Airplane,0.0,1,Personal,Preliminary,0
4,United States,1,Substantial,Airplane,0.0,1,Instructional,Preliminary,0

In [6]:
df = pd.get_dummies(df, columns=["Report Status", "Purpose of Flight", "Aircraft Damage", "Aircraft Category"]
                    , prefix=['Report', 'Purpose', 'Damage', 'Aircraft Category'])
df.head()

,Country,Type,Amateur Built,Number of Engines,Injury Severity,Report_Factual,Report_Foreign,Report_Preliminary,Report_Probable Cause,Purpose_Aerial Application,...,Aircraft Category_Glider,Aircraft Category_Gyrocraft,Aircraft Category_Gyroplane,Aircraft Category_Helicopter,Aircraft Category_Powered Parachute,Aircraft Category_Powered-Lift,Aircraft Category_Rocket,Aircraft Category_Ultralight,Aircraft Category_Unknown,Aircraft Category_Weight-Shift
0,United States,1,1.0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,United States,1,0.0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,United States,1,1.0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,United States,1,0.0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,United States,1,0.0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 81366 entries, 0 to 81365
Data columns (total 47 columns):
Country                                80859 non-null object
Type                                   81366 non-null int64
Amateur Built                          80749 non-null float64
Number of Engines                      81366 non-null int64
Injury Severity                        81366 non-null int64
Report_Factual                         81366 non-null uint8
Report_Foreign                         81366 non-null uint8
Report_Preliminary                     81366 non-null uint8
Report_Probable Cause                  81366 non-null uint8
Purpose_Aerial Application             81366 non-null uint8
Purpose_Aerial Observation             81366 non-null uint8
Purpose_Air Drop                       81366 non-null uint8
Purpose_Air Race/Show                  81366 non-null uint8
Purpose_Banner Tow                     81366 non-null uint8
Purpose_Business                       81366 non-null uint8
Purpose_Executive/Corporate            81366 non-null uint8
Purpose_External Load                  81366 non-null uint8
Purpose_Ferry                          81366 non-null uint8
Purpose_Firefighting                   81366 non-null uint8
Purpose_Flight Test                    81366 non-null uint8
Purpose_Glider Tow                     81366 non-null uint8
Purpose_Instructional                  81366 non-null uint8
Purpose_Other Work Use                 81366 non-null uint8
Purpose_Personal                       81366 non-null uint8
Purpose_Positioning                    81366 non-null uint8
Purpose_Public Aircraft                81366 non-null uint8
Purpose_Public Aircraft - Federal      81366 non-null uint8
Purpose_Public Aircraft - Local        81366 non-null uint8
Purpose_Public Aircraft - State        81366 non-null uint8
Purpose_Skydiving                      81366 non-null uint8
Purpose_Unknown                        81366 non-null uint8
Damage_Destroyed                       81366 non-null uint8
Damage_Minor                           81366 non-null uint8
Damage_Substantial                     81366 non-null uint8
Aircraft Category_Airplane             81366 non-null uint8
Aircraft Category_Balloon              81366 non-null uint8
Aircraft Category_Blimp                81366 non-null uint8
Aircraft Category_Glider               81366 non-null uint8
Aircraft Category_Gyrocraft            81366 non-null uint8
Aircraft Category_Gyroplane            81366 non-null uint8
Aircraft Category_Helicopter           81366 non-null uint8
Aircraft Category_Powered Parachute    81366 non-null uint8
Aircraft Category_Powered-Lift         81366 non-null uint8
Aircraft Category_Rocket               81366 non-null uint8
Aircraft Category_Ultralight           81366 non-null uint8
Aircraft Category_Unknown              81366 non-null uint8
Aircraft Category_Weight-Shift         81366 non-null uint8
dtypes: float64(1), int64(3), object(1), uint8(42)
memory usage: 7.0+ MB

In [9]:
writer = pd.ExcelWriter('./df.xlsx')
df.to_excel(writer,"df")
writer.save()