In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import plotly.plotly as py
import plotly.graph_objs as go

# Machine Learning 
from sklearn.linear_model import LogisticRegression 
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron 
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics 
from sklearn.cross_validation import KFold

/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning:

This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.

In [2]:
path = './Dataset/df.xlsx'

In [3]:
df = pd.read_excel(path)
df.head()

,Country,Type,Amateur Built,Number of Engines,Injury Severity,Report_Factual,Report_Foreign,Report_Preliminary,Report_Probable Cause,Purpose_Aerial Application,...,Aircraft Category_Glider,Aircraft Category_Gyrocraft,Aircraft Category_Gyroplane,Aircraft Category_Helicopter,Aircraft Category_Powered Parachute,Aircraft Category_Powered-Lift,Aircraft Category_Rocket,Aircraft Category_Ultralight,Aircraft Category_Unknown,Aircraft Category_Weight-Shift
0,United States,1,1.0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,United States,1,0.0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,United States,1,1.0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,United States,1,0.0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,United States,1,0.0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 81366 entries, 0 to 81365
Data columns (total 47 columns):
Country                                80859 non-null object
Type                                   81366 non-null int64
Amateur Built                          80749 non-null float64
Number of Engines                      81366 non-null int64
Injury Severity                        81366 non-null int64
Report_Factual                         81366 non-null int64
Report_Foreign                         81366 non-null int64
Report_Preliminary                     81366 non-null int64
Report_Probable Cause                  81366 non-null int64
Purpose_Aerial Application             81366 non-null int64
Purpose_Aerial Observation             81366 non-null int64
Purpose_Air Drop                       81366 non-null int64
Purpose_Air Race/Show                  81366 non-null int64
Purpose_Banner Tow                     81366 non-null int64
Purpose_Business                       81366 non-null int64
Purpose_Executive/Corporate            81366 non-null int64
Purpose_External Load                  81366 non-null int64
Purpose_Ferry                          81366 non-null int64
Purpose_Firefighting                   81366 non-null int64
Purpose_Flight Test                    81366 non-null int64
Purpose_Glider Tow                     81366 non-null int64
Purpose_Instructional                  81366 non-null int64
Purpose_Other Work Use                 81366 non-null int64
Purpose_Personal                       81366 non-null int64
Purpose_Positioning                    81366 non-null int64
Purpose_Public Aircraft                81366 non-null int64
Purpose_Public Aircraft - Federal      81366 non-null int64
Purpose_Public Aircraft - Local        81366 non-null int64
Purpose_Public Aircraft - State        81366 non-null int64
Purpose_Skydiving                      81366 non-null int64
Purpose_Unknown                        81366 non-null int64
Damage_Destroyed                       81366 non-null int64
Damage_Minor                           81366 non-null int64
Damage_Substantial                     81366 non-null int64
Aircraft Category_Airplane             81366 non-null int64
Aircraft Category_Balloon              81366 non-null int64
Aircraft Category_Blimp                81366 non-null int64
Aircraft Category_Glider               81366 non-null int64
Aircraft Category_Gyrocraft            81366 non-null int64
Aircraft Category_Gyroplane            81366 non-null int64
Aircraft Category_Helicopter           81366 non-null int64
Aircraft Category_Powered Parachute    81366 non-null int64
Aircraft Category_Powered-Lift         81366 non-null int64
Aircraft Category_Rocket               81366 non-null int64
Aircraft Category_Ultralight           81366 non-null int64
Aircraft Category_Unknown              81366 non-null int64
Aircraft Category_Weight-Shift         81366 non-null int64
dtypes: float64(1), int64(45), object(1)
memory usage: 29.8+ MB

In [5]:
# To check if there are any missing values in the dataframe and fill the missing data with the median value
df.isnull().any()
df = df.fillna(df.median())

In [6]:
#df.isnull().any()

In [7]:
df_training = df[:70000]
df_testing = df[70000:]

In [8]:
df_testing = df_testing.drop(['Injury Severity','Country'],axis = 1)
X_train = df_training.drop(['Injury Severity','Country'],axis = 1)
Y_train = df_training['Injury Severity']
X_test = df_testing.copy()

In [9]:
X_train.shape, Y_train.shape, X_test.shape

((70000, 45), (70000,), (11366, 45))

## Predictions

In [10]:
## Logistic Regression 

logreg = LogisticRegression()
logreg.fit(X_train, Y_train)
Y_pred = logreg.predict(X_test)
acc_log = round(logreg.score(X_train, Y_train) * 100, 2)
acc_log

88.08

In [11]:
# # # Support Vector Machine 

# svc = SVC()
# svc.fit(X_train, Y_train)
# Y_pred1 = svc.predict(X_test)
# acc_svc = round(svc.score(X_train, Y_train) * 100, 2)
# acc_svc

In [12]:
# # # Decision Tree

# decision_tree = DecisionTreeClassifier()
# decision_tree.fit(X_train, Y_train)
# Y_pred2 = decision_tree.predict(X_test)
# acc_decision_tree = round(decision_tree.score(X_train, Y_train) * 100, 2)
# acc_decision_tree

In [13]:
# # # KNN 

# knn = KNeighborsClassifier(n_neighbors = 3)
# knn.fit(X_train, Y_train)
# Y_pred2 = knn.predict(X_test)
# acc_knn = round(knn.score(X_train, Y_train) * 100, 2)
# acc_knn

In [14]:
prediction = pd.DataFrame({
    'Injury Severity' : Y_pred
})

In [15]:
prediction.head()

   Injury Severity
0                0
1                0
2                0
3                0
4                0

In [16]:
injuries = {0: 'Non-Fatal', 1:'Fatal'}
prediction.replace(injuries, inplace=True)
prediction

      Injury Severity
0           Non-Fatal
1           Non-Fatal
2           Non-Fatal
3           Non-Fatal
4           Non-Fatal
5               Fatal
6           Non-Fatal
7               Fatal
8           Non-Fatal
9           Non-Fatal
10              Fatal
11          Non-Fatal
12          Non-Fatal
13          Non-Fatal
14          Non-Fatal
15          Non-Fatal
16          Non-Fatal
17          Non-Fatal
18          Non-Fatal
19              Fatal
20              Fatal
21              Fatal
22          Non-Fatal
23              Fatal
24              Fatal
25          Non-Fatal
26              Fatal
27          Non-Fatal
28          Non-Fatal
29          Non-Fatal
...               ...
11336       Non-Fatal
11337           Fatal
11338       Non-Fatal
11339       Non-Fatal
11340       Non-Fatal
11341           Fatal
11342           Fatal
11343       Non-Fatal
11344       Non-Fatal
11345           Fatal
11346           Fatal
11347           Fatal
11348           Fatal
11349           Fatal
11350       Non-Fatal
11351       Non-Fatal
11352       Non-Fatal
11353           Fatal
11354       Non-Fatal
11355       Non-Fatal
11356       Non-Fatal
11357       Non-Fatal
11358       Non-Fatal
11359           Fatal
11360       Non-Fatal
11361           Fatal
11362           Fatal
11363           Fatal
11364           Fatal
11365           Fatal

[11366 rows x 1 columns]

In [17]:
df_testing.to_excel('./Dataset/Testing Data.xlsx', index=False)
df_training.to_excel('./Dataset/Training Data.xlsx', index=False)
prediction.to_excel('./Dataset/Results.xlsx', index=False)